colors = require('colors')

{charset, isArray, str, entity, dict, list2dict, extendSyntaxInfo} = require '../utils'

{extend, firstIdentifierChars, firstIdentifierCharSet, letterDigitSet, identifierChars,
digitCharSet, letterCharSet, identifierCharSet, firstSymbolCharset
taijiIdentifierCharSet, constant} = base = require './base'
digitChars = base.digits
letterChars = base.letters

{NUMBER,  STRING,  IDENTIFIER, SYMBOL, REGEXP,  HEAD_SPACES, CONCAT_LINE, PUNCTUATION, FUNCTION, C_BLOCK_COMMENT
PAREN, BRACKET, DATA_BRACKET, CURVE, INDENT_EXPRESSION
NEWLINE,  SPACES,  INLINE_COMMENT, SPACES_INLINE_COMMENT,
LINE_COMMENT, BLOCK_COMMENT, CODE_BLOCK_COMMENT,CONCAT_LINE
NON_INTERPOLATE_STRING, INTERPOLATE_STRING, EOI
INDENT, UNDENT, HALF_DENT, MODULE_HEADER, MODULE, SPACE_COMMENT, TAIL_COMMENT
SPACE, HASH, RIGHT_DELIMITER, KEYWORD, CONJUNCTION
CODE_BLOCK_COMMENT_LEAD_SYMBOL
PREFIX, SUFFIX, BINARY
END_INTERPOLATED_STRING

OPERATOR_EXPRESSION, COMPACT_CLAUSE_EXPRESSION, SPACE_CLAUSE_EXPRESSION, INDENT_EXPRESSION

} = constant

{prefixOperatorDict, suffixOperatorDict, binaryOperatorDict, makeExpression} = require './operator'

exports.escapeNewLine = escapeNewLine = (s) -> (for c in s then (if c=='\n' then '\\n' else '\\r')).join('')

exports.keywordMap = keywordMap =
  'if': 1, 'try':1, 'switch':1, 'while':1, 'let':1, 'letrec!':1, 'letloop!':1, 'do':1, 'repeat':1
  'return':1, 'break':1, 'continue':1, 'throw':1,'function':1,'for':1
  'loop':1, 'class':1, 'var':1, 'for':1

keywordHasOwnProperty = Object.hasOwnProperty.bind(exports.keywordMap)

exports.isKeyword = isKeyword = (item) ->
  item and not item.escaped and hasOwnProperty.call(exports.keywordMap, item.text)

exports.conjMap = conjMap =
  'then':1, 'else':1, 'catch':1, 'finally':1, 'case':1, 'default':1, 'extends': 1
  'until':1, 'where':1, 'when':1
conjunctionHasOwnProperty = Object.hasOwnProperty.bind(exports.keywordMap)

exports.isConjunction = isConjunction = (item) ->
  item and not item.escaped and hasOwnProperty.call(exports.conjMap, item.text)

hasOwnProperty = Object::hasOwnProperty

begin = (exp) ->
  if not exp or not exp.push then return exp
  if exp.length==0 then ''
  else if exp.length==1 then exp[0]
  else exp.unshift('begin!'); exp

exports.Parser = ->
  parser = @; @predefined = predefined = {}
  unchangeable = ['cursor', 'setCursor', 'lineno', 'setLineno', 'atLineHead', 'atStatementHead', 'setAtStatementHead']

  # global variable used by lexer
  text = '' # text to be parsed
  cursor = 0 # position pointer while do lexical parsing, use cur for local position pointer
  char = '' # current character, should assure char is the value of text[cursor] whenerver entering or leaving a function
  lineno = 0 # current line number, use line for local line number
  lineStart = 0 # start cursor of current line
  lexIndent = 0 # global lexical indent column of current line, use dent for local indent column
  indent = 0 # global indent while parsing, get from tokens including SPACE, NEWLINE, INDENT, UNDENT, EOI
  atLineHead = true # global indicator to tell whether cursor is at the head of a line before any non space character
  interolateStringNumber = 0 # when entering interpolate string, increment by 1, when leaving, decrement by 1. when entering paren etc, multiplied by 2, when leaving, divided by 2 if even, (x-1)/2 if odd.

  # token should have the field: type, value, cursor, stopCursor, line, column
  # token like SPACE, NEWLINE, INDENT, UNDENT should have the field "indent" which means the indent of the end line of the token
  token = undefined # global token generated by lexical parsing and used by the parser

  # global variable used by the syntax parser
  memoMap = {} # memorize the result for syntax matcher
  atStatementHead = true # whether is at head of statement
  environment = null # compiler environment used by dynamic evaluation while parsing
  endCursorOfDynamicBlockStack = [] # used by "then" block of ? clause to identifier end of dynamic block

  memoIndex = 0  # don't need be set in parser.init, memoMap need to be set instead.

  eof = {type:EOI, value:'', cursor: text.length, column: -1, indent: -1} # line wait to be filled
  eof.next = eof  # eof.next is always itself

  nextToken = ->
    if token.next
      indent = token.indent or indent
      token = token.next
    else
      if not char
        if token==eof then return eof
        eof.lineno = lineno+1; lineStart = cursor; lexIndent = -1
        token.next = eof
        return token = eof # while reaching the end of input, always return eof
      else if fn = tokenFnMap[char] then return token=fn(char)
      else return token=tokenOnSymbolChar()

  #  tokenFnMap[char](char) and tokenOnSymbolChar should change the token
  @matchToken = matchToken = ->
    if not char
      if token==eof then return eof
      eof.lineno = lineno+1; lineStart = cursor; lexIndent = -1
      token.next = eof
      return token = eof # while reaching the end of input, always return eof
    else if fn = tokenFnMap[char] then return token=fn(char)
    else return token=tokenOnSymbolChar()

  @token = -> token

  @tokenFnMap = tokenFnMap = {}

  tokenOnSymbolChar = ->
    cur = cursor
    while char
      if symbolStopChars[char] then break

      # //, /*, /!
      # "/!" always start a regexp
      if char=='/' and ((c2=text[cursor+1])=='/' or c2=='*' or c2=='!') then break
      # else if c2=='.' # should not reach here, because this /. is always in the middle of the symbol, not in the front
      # "\" should not be concatenated symbol if following symbol characters
      #else if char=='\\' and ((c2=text[cursor+1])=='\n'  or c2=='\r') then break
      char = text[++cursor]

    token.next = {type:SYMBOL, value: text.slice(cur, cursor),
    cursor:cur, stopCursor:cursor, line: lineno, column:cursor-lineStart}

  symbolStopChars = extend charset(' \t\v\n\r()[]{},;:\'\".@\\'), identifierCharSet

  tokenFnMap['@'] = tokenFnMap['.'] = tokenOnAtChar = ->
    cur = cursor; column = cursor-lineStart; first = char; char = text[++cursor]
    while char==first then char = text[++cursor]
    token.next = {type: SYMBOL, value: text.slice(cur, cursor),
    cursor:cur, stopCursor:cursor,
    line: lineno, column:column, atom:cursor-cur==1}

  tokenFnMap[':'] = tokenOnColonChar = ->
    cur = cursor; column = cursor-lineStart; first = char; char = text[++cursor]
    while char==first then char = text[++cursor]
    if cursor==cur+1 then type = PUNCTUATION else type = SYMBOL
    token.next = {type:type, value: text.slice(cur, cursor), atom:cursor-cur==2
    cursor:cur, stopCursor:cursor,
    line: lineno, column:column}

    # the word "space" below maybe means not spacebar key or space character ' ' or '\t'
  # it means anything piece like white space, e.g. ' ', '\t', etc.

  concatenateLine = ->
    cur = cursor-1; column = cursor-lineStart; indent = lexIndent
    if char=='\n'
      char = text[++cursor]
      if char=='\r' then char = text[++cursor]
    else if char=='\r'
      char = text[++cursor]
      if char=='\n' then char = text[++cursor]
    lineStart = cursor
    while (char=text[cursor]) and char==' ' then cursor++
    if char=='\t' then error 'do not allow use tab character "\t" at the head of line.'
    else if char=='\n' or char=='\r' then error 'should not follow empty line as concatenated line'
    else if not char then error 'unexpected end of input after concatenated line symbol "\"'
    lexIndent = cursor-lineStart
    if lexIndent<indent then error 'expect the same indent or more indent for the concatenated lines'
    skipInlineSpace()
    if (char=text[cursor])=='\n' or char=='\r'
      error 'concatenated line should not have only spaces and comments'
    return token.next = {type:SPACE, cursor:cur, stopCursor: cursor, line:line, stopLine:lineno, column:column, indent:lexIndent}

  # token started with ' ' and '\t'
  tokenFnMap[' '] = tokenFnMap['\t'] = tokenOnSpaceChar = ->
    cur = cursor; line = lineno; column = cursor-lineStart; dent = lexIndent
    char = text[++cursor]
    skipInlineSpace(dent)
    if char=='\\'
      char = text[++cursor]
      if char=='\n' or c=='\r'
        token.next = tkn = concatenateLine()
        tkn.cursor = cur; tkn.column = column; tkn.value = text[cur...cursor]
        return tkn
      else
        cursor--
        return  token.next = {type:SPACE, value:text[cur...cursor], cursor:cur, stopCursor: cursor,
        line:line, stopLine:lineno, column:column, indent:lexIndent}
    else if char=='\n' or char=='\r'
      skipSpaceLines(dent)
      if not char then type = EOI
      else if lexIndent>dent then type = INDENT
      else if lexIndent<dent then type = UNDENT
      else type = NEWLINE
      return token.next = {type:type, value:text[cur...cursor], cursor:cur, line:line, column:column, indent:lexIndent}
    else
      return  token.next = {type:SPACE, value:text[cur...cursor], cursor:cur, stopCursor: cursor,
      line:line, stopLine:lineno, column:column, indent:lexIndent}

  # should be called after a new line
  skipSpaceLines = (dent) ->
    if char=='\n'
      char = text[++cursor]
      if char=='\r' then char = text[++cursor]
    else if char=='\r'
      char = text[++cursor]
      if char=='\n' then char = text[++cursor]
    lineStart = cursor
    while 1
      if not char then return
      while char and char==' ' then cursor++; char = text[cursor]
      if char=='\t' then unexpectedTabCharAtLineHead()
      else if char=='\n'
        if char=='\r' then cursor += 2 else cursor++
        char = text[cursor];  lineno++; lineStart = cursor
        continue
      else if char=='\r'
        if char=='\n' then cursor += 2 else cursor++
        char = text[cursor];  lineno++; lineStart = cursor
        continue
      else if not char then break
      else if (lexIndent=cursor-lineStart)!=dent then break
      else if char=='/'
        if (c2=text[cursor+1])=='/'
          cursor += 2; char = text[cursor]
          # skip line tail
          while (char=text[cursor]) and char!='\n' and char!='\r' then cursor++; char = text[cursor]
          continue
        # indent block comment /. ... /
        else if c2=='.'
          if atLineHead then leftIndentBlockComment(dent); continue
          else break # will be normal symbol
        else if c2=='*'
          cursor += 2; char = text[cursor]; leftCBlockComment()
          skipInlineSpace()
          if char=='\n'
            if char=='\r' then cursor += 2 else cursor++
            char = text[cursor];  lineno++; lineStart = cursor
            continue
          else if char=='\r'
            if char=='\n' then cursor += 2 else cursor++
            char = text[cursor];  lineno++; lineStart = cursor
            continue
          else break

        # regexp /! ... /
        else if c2=='!' then break

        # else if atLineHead then break # switch to tokenOnForwardSlashChar to process code block comment start symbol
        else break
      else break
    return

  # skipInlineSpace is called by tokenOnSpaceChar
  # skiptInlineSpace should not generate independent token and called independently
  skipInlineSpace = (dent) ->
    while 1
      while char==' ' or char=='\t' then char = text[++cursor]
      if char=='/'
        if (c2=text[cursor+1])=='*' then cursor +=2; char = text[cursor]; leftCBlockComment(dent); continue
        if c2=='/'
          # don't need to process column here, because want to skip characters until reaching new line
          cursor += 2; char = text[cursor]          
          while char!='\n' and char!='\r' then char = text[++cursor]; continue
          break
      break

  # \n\r, \r\n, \r, \n, don't eat spaces.
  @newline = newline = ->
    if (c=char)=='\r'
      cursor++;
      if (c2=text[cursor])=='\n' then cursor++; c2 = '\n'
      char = text[cursor]; lineno++; lineStart = cursor
    else if char=='\n'
      cursor++
      if (c2=text[cursor])=='\r' then cursor++; c2 = '\r'
      char = text[cursor]; lineno++; lineStart = cursor
    else return
    c+(c2 or '')

  # left indent block comment started with /., before entering this function, /. has been matched.
  leftIndentBlockComment = (dent) ->
    # skip line tail
    while char!='\n' and char!='\r' then cursor++; char = text[cursor]

    # skip lines that is empty or indent more spaces at the head
    while 1
      if char=='\n'
        if text[cursor+1]=='\r' then cursor+=2 else cursor++
        char = text[cursor]; lineno++; lineStart = cursor
        while char==' ' then cursor++; char = text[cursor]
        if char=='\n' or char=='\r' then continue
        if char=='\t' then unexpectedTabCharAtLineHead()
        if cursor-lineStart<=dent then break
      else if char=='\r'
        if text[cursor+1]=='\n' then cursor+=2 else cursor+=1
        char = text[cursor]; lineno++; lineStart = cursor
        while char==' ' then cursor++; char = text[cursor]
        if char=='\n' or char=='\r' then continue
        if char=='\t' then unexpectedTabCharAtLineHead()
        if cursor-lineStart<=dent then break
      else if not char then break

  # default /* some content */, can cross lines
  leftCBlockComment = (dent) ->
    # dent: the indent column of the line of '/*'
    while 1
      if char=='*' and text[cursor+1]=='/' then cursor += 2;  char = text[cursor]; break
      else if char=='\n'
        cursor++;  char = text[cursor]; lineno++
        if char=='\r' then cursor++;  char = text[cursor];
        lineStart = cursor
        while char==' ' then cursor++;  char = text[cursor]
        if char=='\t' then unexpectedTabCharAtLineHead()
        if char=='\n' or char=='\r' then continue
        else if not char then unexpectedEOI('while parsing c style block comment /* */')
        if lineStart-cursor<dent then expectMoreIndent(dent, 'while parsing c style block comment /* */')
      else if char=='\r'
        cursor++;  char = text[cursor]; lineno++
        if char=='\n' then cursor++; char = text[cursor]
        lineStart = cursor
        while char==' ' then cursor++;  char = text[cursor]
        if char=='\t' then unexpectedTabCharAtLineHead()
        if char=='\n' or char=='\r' then continue
        else if not char then unexpectedEOI('while parsing c style block comment /* */')
        if lineStart-cursor<dent then expectMoreIndent(dent)
      else if not char
        unexpectedEOI('while parsing c style block comment /* */')
      else cursor++;  char = text[cursor]

  leftRegexp = ->
    while char
      if char=='\\'
        if (c2=text[cursor+1]=='/') or c2=='\\' then cursor += 2; char = text[cursor]
        else char = text[cursor++]
      else if char=='\n' or char=='\r'
        error 'meet unexpected new line while parsing regular expression'
      else if char=='/'
        i = 0; char = text[++cursor]
        # console.log text.slice(cursor)
        while char
          if char=='i' or char=='g'or char=='m' then char = text[++cursor]; ++i
          else break
          if i>3 then error 'too many modifiers "igm" after regexp'
        return
      else char = text[++cursor]
    if not char then error 'unexpected end of input while parsing regexp'

  # back slash \ can be used to escape keyword, conjunction, symbol
  tokenFnMap['\\'] = tokenOnBackSlashChar = ->
    cur = cursor; column = cursor-lineStart; char = text[++cursor]
    if char=='\n' or char=='\r'
      token.next = tkn = concatenateLine()
      tkn.cursor = cur; tkn.column = column; tkn.value = text[cur...cursor]
      return tkn
    line = lineno
    if firstIdentifierCharSet[char]
      tkn = tokenOnIdentifierChar()
      tkn.escaped = true; tkn.cursor = cur
      return token.next = tkn
    else if firstSymbolCharset[char]
      tkn = tokenOnSymbolChar()
      tkn.escaped = true; tkn.cursor = cur; token.value = '\\'+token.value
      return token.next = tkn
    else if char==':'
      tkn = tokenOnColonChar()
      tkn.value = '\\'+tkn.value
      tkn.escaped = true; tkn.cursor = cur
      return token.next = tkn
    else if char=='@'
      tkn = tokenOnAtChar()
      tkn.value = '\\'+tkn.value
      tkn.escaped = true; tkn.cursor = cur
      return token.next = tkn
    else if char=='.'
      tkn = tokenOnDotChar()
      tkn.value = '\\'+tkn.value
      tkn.escaped = true; tkn.cursor = cur
      return token.next = tkn
    else if char=="'"
      tkn = tokenOnSingleQuoteChar()
      if text[cur+2]=="'" and text[cur+3]=="'"
        # do not escape '''...'''
        char = text[++cursor]
        return token.next = {type:SYMBOL, value:'\\', cursor:cur, stopCursor:cursor
        line:lineno, column:cur-lineStart, indent:lexIndent
        next:tkn}
      else
        for c in text[cur+2...tkn.stopCursor]
          if c=='\n' or c=='\r' then error 'unexpected new line characters in escaped string'
        tkn.escaped = true; tkn.cursor = cur; tkn.atom = true
        return token.next = tkn
    # else if char=='"' # don't permit escape interpolated string
    else
      while char=text[++cursor]=='\\' then true
      return token.next = {type:SYMBOL, value:text[cur...cursor], cursor:cur, stopCursor:cursor
      line:lineno, column:cur-lineStart}

  tokenFnMap['/'] = tokenOnForwardSlashChar = ->
    cur = cursor; column = cursor-lineStart; char = text[++cursor]; line = lineno; indent = lexIndent
    # // start a line comment
    if char=='/' # // leading line comment
      # skip line tail
      cursor++; char=text[cursor]
      while char and char!='\n' and char!='\r' then cursor++; char=text[cursor]
      skipSpaceLines(indent)
      if not char then type = EOI
      else if lexIndent>indent then type = INDENT
      else if lexIndent==indent then type = NEWLINE
      else type = UNDENT
      return token.next = {type:type, value: text[cur...cursor], cursor:cur, stopCursor:cursor, line:line, column:column, indent:lexIndent}
    # /* start a c style block comment
    else if char=='*'
      leftCBlockComment()
      skipInlineSpace()
      if not char then t = EOI
      else if char=='\n' or char=='\r'
        skipSpaceLines(indent)
        if not char then type = EOI
        else if lexIndent>indent then type = INDENT
        else if lexIndent==indent then type = NEWLINE
        else type = UNDENT
        return token.next = {type:type, value: text[cur...cursor], cursor:cur, stopCursor:cursor, line:line, column:column, indent:lexIndent}
      else
        type = SPACE
        return token.next = {type:type, value: text[cur...cursor], cursor:cur, stopCursor:cursor, line:line, stopLine:lineno, column:column, indent:lexIndent}
    # /! start a regexp
    else if char=='!'
      cur = cursor; cursor += 2; char = text[cursor]; column = cursor-lineStart
      leftRegexp()
      return token.next = {type:REGEXP, value:['regexp!', '/'+text[cur+1...cursor]], atom:true, cursor:cur, stopCursor:cursor, line:lineno, column: column}
    else if char=='.' # block comment /. multiple indented lines
      # block comment should never be generated at match_here
      # how to assure it?
      # when starting parsing the module body, use tokenOnSpaceChar to generate the first token
      # and then, only parse /. as indented block
      # but with global variable atLineHead, we do defensive style coding and simplify the design
      if atLineHead
        char = text[++cursor]
        leftIndentBlockComment(indent)
        skipSpaceLines(indent)
        if lexIndent>indent then t = INDENT
        else if lexIndent==indent then t = NEWLINE
        else t = UNDENT
        return token.next = {type: t, value: text[cur...cursor], cursor:cur, stopCursor:cursor, line:line, column:column}
      else
        # "/" return as independent symbol, left "." will be processed later, it and following "." maybe will become a symbol too.
        # a possible legal syntax is that "/" is used as a suffix operator and "." or ".." or "..." are used as a binary operator.
        # e.g. a/...b
        return token.next = {type: SYMBOL, value:"/", cursor:cur, stopCursor:cursor, line:line, column:column}
    else if atLineHead
      # the '/' at the head of one line should start a code block comment
      # which should be processed when meeting new line
      return token.next = {type:CODE_BLOCK_COMMENT_LEAD_SYMBOL, value:"/", cursor:cur, stopCursor:cursor, line:line, column:column}
    else
      # a symbol starts with "/"
      char = text[++cursor]; prev = token; tokenOnSymbolChar(); value = "/"+token.value
      token = {type:SYMBOL, value:value, cursor:cur, stopCursor:cursor, line:line, column:column}
      return prev.next = token

  # the token leaded by '\n', '\r', maybe return token with type NEWLINE, INDENT, UNDENT, EOI
  tokenFnMap['\n'] = tokenFnMap['\r'] = tokenOnNewlineChar = ->
    cur = cursor; line = lineno; column = cursor-lineStart; indent = lexIndent
    skipSpaceLines(indent)
    if not char then type = EOI
    else if lexIndent>indent then type = INDENT
    else if lexIndent==indent then type = NEWLINE
    else type = UNDENT
    return token.next = {type:type, value:text[cur...cursor],
    cursor:cur, stopCursor:cursor,
    line:line, column:column, indent:lexIndent}

  tokenOnIdentifierChar = ->
    cur = cursor; char = text[++cursor]; column = cursor-lineStart
    while char and identifierCharSet[char] then char=text[++cursor]
    txt=text.slice(cur, cursor)
    if keywordHasOwnProperty(txt) then type = KEYWORD
    else if conjunctionHasOwnProperty(txt) then type = CONJUNCTION
    else type = IDENTIFIER
    token.next = {type:type, value:txt, atom:true
    cursor:cur, stopCursor: cursor,
    line: lineno, column: column}

  for c of firstIdentifierCharSet then tokenFnMap[c] = tokenOnIdentifierChar

  tokenOnNumberChar = ->
    cur = cursor; base = 10; column = cursor-lineStart
    if char=='0' and c2 = text[cursor+1]
      if c2=='b' or c2=='B' then base = 2; baseStart = cursor += 2; char = text[cursor]
      else if c2=='x' or c2=='X' then base = 16; baseStart = cursor += 2; char = text[cursor]
      else char = text[++cursor]; meetDigit = true
    if base==2
      while char
        if char=='0' or char=='1' then char = text[++cursor]
        else break
    else if base==16
      while char
        if  not('0'<=char<='9' or 'a'<=char<='f' or 'A'<=char<='F') then break
        else char = text[++cursor]
    if base==2
      if char=='.' or char=='e' or char=='E' then error 'binary number followed by ".eE"'
      else if '2'<=char<='9' then error 'binary number followed by 2-9'
    if base==16
      if char=='.' then error 'hexadecimal number followed by "."'
      else if letterCharSet[char] then error 'hexadecimal number followed by g-z or G-Z'
    if base!=10
      if cursor==baseStart
        # e.g 0x+3, 0x(1+2)
        cursor--; char = text[cursor]
        return token.next = { type: NUMBER, value:parseInt(text[baseStart...cursor], base), atom:true
        cursor:cur, stopCursor:cursor
        line:lineno, column:column}
      else
        return token.next = { type: NUMBER, value:parseInt(text[baseStart...cursor], base), atom:true
        cursor:cur, line:lineno, column: column}
    # base==10
    while char
      if '0'<=char<='9' then meetDigit = true; char = text[++cursor]
      else break
    # if not meetDigit then return symbol() # comment because in no matchToken solution
    if not meetDigit then return
    if char=='.'
      meetDigit = false
      char = text[++cursor]
      while char
        if char<'0' or '9'<char then break
        else meetDigit = true; char = text[++cursor]
    dotCursor = cursor-1
    if not meetDigit and char!='e' and char!='E'
      cursor = dotCursor; char = text[cursor]
      return token.next = { type: NUMBER, value:parseInt(text[baseStart...cursor], base), atom:true
      cursor:cur, stopCursor:cursor
      line:lineno, column: column}
    if char=='e' or char=='E'
      char = text[++cursor]
      if char=='+' or char=='-'
        char = text[++cursor]
        if not char or char<'0' or '9'<char
          cursor = dotCursor; char = text[cursor]
          return token.next = { type: NUMBER, value:parseInt(text[cur...dotCursor], base), atom:true
          cursor:cur, stopCursor:cursor
          line:lineno, column: column}
        else
          while char
            char = text[++cursor]
            if  char<'0' or '9'<char then break
      else if not char or char<'0' or '9'<char
        cursor = dotCursor; char = text[cursor]
        return token.next = { type: NUMBER, value:parseInt(text[cur...dotCursor], base), atom:true
        cursor:cur, stopCursor:cursor
        line:lineno, column: column}
      else while char
          if  char<'0' or '9'<char then break
          char = text[++cursor]
    token.next = { type: NUMBER, value:parseFloat(text[cur...cursor], base), atom:true
    cursor:cur, stopCursor:cursor
    line:lineno, column: column}

  for c in '0123456789' then tokenFnMap[c] = tokenOnNumberChar

  tokenFnMap[','] =tokenOnCommaChar = ->
    cur = cursor; char = text[++cursor]
    token.next = {type:PUNCTUATION, value:',', line:lineno, cursor:cursor, stopCursor:cursor, column: cur-lineStart}

  tokenFnMap[';'] = tokenOnSemiColonChar = ->
    cur = cursor; char = text[++cursor]
    token.next = {value:';', type:PUNCTUATION
    cursor:cursor, stopCursor:cursor, line:lineno, column: cur-lineStart}

  # whether new line character is immediately following a concatenating character '\'
  # this is not affected embedded concatenated line in other structure.
  concatenating = false

  tokenFnMap["'"] = tokenOnSingleQuoteChar = ->
    char = text[++cursor]; column = cursor-lineStart
    if char=="'"
      if text[cursor+1]=="'"
        cursor += 2; char = text[cursor]
        return token.next = leftRawNonInterpolatedString()
      else
        char = text[++cursor]
        return token.next = {value:'""', type:NON_INTERPOLATE_STRING, atom:true, cursor:cursor-2, line:lineno, column:column}
    else return token.next = leftNonInterpolatedString()

  leftRawNonInterpolatedString = ->
    cur = cursor-3; line = lineno
    if cursor==indent+3 then indentInfo = {indent:lexIndent}
    else indentInfo = {}
    str = ''
    # the left characters of the same line after '''
    while char
      if char=="'"
        if text[cursor+1]=="'"
          if text[cursor+2]=="'"
            cursor += 3; char = text[cursor]
            return {type:NON_INTERPOLATE_STRING, value:'"'+str+'"', atom:true, start:cur, stop:cursor, line:line, stopLine: lineno}
          else str += "''"; cursor += 2; char = text[cursor]
        else str += "'"; char = text[++cursor]
      else if char=='\\'
        # the '\' at end of line will not in the result string
        if (c=text[cursor+1])=='\n' or c=='\r'
          char = text[++cursor]; concatenating = true; break
        else str += '\\\\'; char = text[++cursor]
      else if char!='\n' and char!='\r' then str += char; char = text[++cursor]
      else break
    while char
      if char=="'"
        if text[cursor+1]=="'"
          if text[cursor+2]=="'"
            cursor += 3; char = text[cursor]
            return {type: NON_INTERPOLATE_STRING, value: '"'+str+'"', atom:true, start:cur, stop:cursor, line:line, stopLine: lineno}
          else str += "''"; cursor += 2; char = text[cursor]
        else str += "'"; char = text[++cursor]
      else str += rawNonInterpolatedStringLine(indentInfo)
    if not text[cursor] then error "expect ''', unexpected end of input while parsing interpolated string"

  rawNonInterpolatedStringLine = (indentInfo) ->
    result = ''
    # new line character must be escaped.
    if char=='\n'
      if not concatenating then result += '\\n'
      char = text[++cursor]
      if char=='\r'
        if not concatenating then result += '\\r'
        char = text[++cursor]
    else
      if not concatenating then result += '\\r'
      char = text[++cursor]
      if char=='\n'
        if not concatenating then result += '\\n'
        char = text[++cursor]
    concatenating = false
    lineno++; cur = cursor
    while char==' ' then char = text[++cursor]
    column = cursor-lineStart
    if char=='\t' then error 'unexpected tab character "\t" at the head of line'
    else if char=='\n' or char=='\r' then result += text[cur...cursor]; return result
    else if (ind=indentInfo.value)!=undefined then indentInfo.value = column
    else if ind>column then i = 0; n = column-ind; while i++<n then result += ' '
    else if ind<column then error 'expect equal to or more than the indent of first line of the string'
    while char
      if char=="'"
        if text[cursor+1]=="'"
          if text[cursor+2]=="'" then return result
          else result += '\\"\\"'; cursor += 2; char = text[cursor]
        else result += '\\"'; char = text[++cursor]
      else if char=='\n' or char=='\r' then return result
      else if char=='\\'
        char = text[++cursor]
        if char=='\n' or char=='\r' then concatenating = true; return result
        if char then result += '\\\\'
        else error 'unexpected end of input while parsing non interpolated string'
      # '"' must be escaped, because all the string is wrapped in "..."
      else result += char; char = text[++cursor]
    error 'unexpected end of input while parsing non interpolated string'

  leftNonInterpolatedString = ->
    cur = cursor-1; line = lineno; column = cur-lineStart
    if cursor==indent+1 then indentInfo = {value:indent}
    else indentInfo = {}
    str = ''
    # the left characters of the same line after '''
    while char
      if char=="'"
        char = text[++cursor]
        return {type: NON_INTERPOLATE_STRING, value: '"'+str+'"', atom:true, cursor:cur, stopCursor:cursor, line:line, stopLine:lineno, column:column}
      else if char=='\\'
        # the '\' at end of line will not in the result string
        if (c=text[cursor+1])=='\n' or c=='\r' then char = text[++cursor]; concatenating = true; break
        else if c=="'" then str += "'"; cursor += 2; char = text[cursor]
        else str += '\\'; char = text[++cursor]
      else if char!='\n' and char!='\r' then str += char; char = text[++cursor]
      else break
    while char and char!="'" then str += nonInterpolatedStringLine(indentInfo)
    if char=="'"
      char = text[++cursor]
      return {type: NON_INTERPOLATE_STRING, value: '"'+str+'"', atom:true, cursor:cur, stopCursor:cursor, line:line, stopLine:lineno, column:column}
    else error "expect \"'\", unexpected end of input while parsing interpolated string"

  nonInterpolatedStringLine = (indentInfo) ->
    result = ''
    if char=='\n'
      if not concatenating then result += '\\n'
      char = text[++cursor]
      if char=='\r'
        result += '\\r'
        char = text[++cursor]
    else
      if not concatenating then result += '\r'
      char = text[++cursor]
      if char=='\\n'
        if not concatenating then result += '\\n'
        char = text[++cursor]
    concatenating = false
    lineno++; cur = cursor
    while char==' ' then char = text[++cursor]
    column = cursor-lineStart
    if char=='\t' then error 'unexpected tab character "\t" at the head of line'
    else if char=='\n' or char=='\r' then result += text[cur...cursor]; return result
    else if (ind=indentInfo.value)!=undefined then indentInfo.value = column
    else if ind>column then i = 0; n = column-ind; while i++<n then result += ' '
    else if ind<column then error 'expect equal to or more than the indent of first line of the string'
    while char
      if char=="'" then return result
      else if char=='\n' or char=='\r' then return result
      else if char=='\\'
        char = text[++cursor]
        # '\' at the end of line is omitted
        if char=='\n' or char=='\r' then return result
        else if char=="'" then result += "'"; char = text[++cursor]
        else if char then result += '\\'; result += char; char = text[++cursor]
        else error 'unexpected end of input while parsing non interpolated string'
      else if char=='"'  then result += '\\"'; char = text[++cursor]
      else result += char; char = text[++cursor]
    error 'unexpected end of input while parsing non interpolated string'

  tokenFnMap['"'] = tokenOnDoubleQuoteChar = ->
    char = text[++cursor]
    if char=='"'
      if text[cursor+1]=='"'
        cursor += 2; char = text[cursor]; tkn = token; interolateStringNumber++
        tkn2 = leftRawInterpolateString()
        interolateStringNumber--; tkn.next = tkn2
        return tkn2
      else
        char = text[++cursor]
        return token.next = {value:'""', type:NON_INTERPOLATE_STRING, atom:true, line:lineno, cursor:cursor-2, column:cursor-2-lineStart}
    else
      tkn = token;  interolateStringNumber++
      tkn2 = leftInterpolateString()
      interolateStringNumber--; tkn.next = tkn2
      return tkn2

  @leftRawInterpolateString = leftRawInterpolateString = ->
    cur = cursor; line = lineno
    if cursor-lineStart==indent+3 then indentInfo = {value:indent} else indentInfo = {}
    pieces = []; str = '"'
    while char
      if char=='"'
        if text[cursor+1]=='"'
          if text[cursor+2]=='"'
            cursor += 3
            if str!='"' then pieces.push str += '"'
            return {type: INTERPOLATE_STRING, value: ['string!'].concat(pieces), atom:true
            cursor:cur, stopCursor: cursor,
            line:line, stopLine: line}
          else cursor += 2; char = text[cursor]
        else str += '"'; char = text[++cursor]
      else if char=='\n'
        if not concatenating then str += '\\n'
        char = text[++cursor]
        if char=='\r'
          if not concatenating then str += '\\r'
          char = text[++cursor]
        concatenating = false
        while 1
          lineno++
          while char==' ' then str += char; char = text[++cursor]
          if char=='\n'
            str += '\\n'; char = text[++cursor]
            if char=='\r' then str += '\\r'; char = text[++cursor]
            continue
          else if char=='\r'
            str += '\\r'; char = text[++cursor]
            if char=='\n' then str += '\\n'; char = text[++cursor]
            continue
          else break
        column = cursor-lineStart
        if char=='\t' then error 'unexpected tab character "\t" in the head of line'
        if indentInfo.value==undefined then indentInfo.value = column
        ind = indentInfo.value
        if ind<column then error 'expect equal to or more than the indent of first line of the string'
        else if ind>column then i = 0; n = column-ind; while i++<n then str += ' '
      else if char=='\r'
        if not concatenating then str += '\\r'
        char = text[++cursor]
        if char=='\n'
          if not concatenating then str += '\\n'
          char = text[++cursor]
        concatenating = false
        while 1
          lineno++
          while char==' ' then str += char; char = text[++cursor]
          if char=='\n'
            str += '\\n'; char = text[++cursor]
            if char=='\r' then str += '\\r'; char = text[++cursor]
            continue
          else if char=='\r'
            str += '\\r'; char = text[++cursor]
            if char=='\n' then str += '\\n'; char = text[++cursor]
            continue
          else break
        column = cursor-lineStart
        if char=='\t' then error 'unexpected tab character "\t" in the head of line'
        else if (ind=indentInfo.value)!=undefined then indentInfo.value = column
        else if ind>column then i = 0; n = column-ind; while i++<n then str += ' '
        else if ind<column then error 'expect equal to or more than the indent of first line of the string'
      else if char=='(' or char=='{' or char=='['
        # for efficiency, do not match next token while matching delimiter token (...), [...], {...} in tokenOnLeftParenChar, tokenOnLeftBracketChar, tokenOnLeftCurveChar
        str += char+'"'; pieces.push str; pieces = '"'; char = text[++cursor]
        matchToken()
        char = text[--cursor] # let )]} can be output into next piece
        pieces.push token
      else if  char=='$'
        if (char=text[++cursor])
          if not firstIdentifierCharSet[char] then str += '$'
          else char = '$'; --cursor; pieces.push str+'"'; str = '"'
        else break
      else if char=='$'
        literalStart = ++cursor; char = text[cursor]
        if not firstIdentifierCharSet[char] then str += '$'
        else
          x = parser.interpolateExpression()
          if text[cursor]==':'
            char = text[++cursor]
            pieces.push str+text[literalStart...cursor]+'"'; str = '"'
          else if str!='"' then pieces.push str+'"'; str = '"'
          pieces.push x
      else if char=='\\'
        char = text[++cursor]
        if char=='\n' or char=='\r' then concatenating = true
        else if char then str += '\\\\'
        else error 'unexpected end of input while parsing interpolated string'
      else str += char; char = text[++cursor]
    if not text[cursor] then error 'expect \'"\', unexpected end of input while parsing interpolated string'

  leftInterpolateString = ->
    cur = cursor-1; line = lineno
    if cursor-1-lineStart==indent+1 then indentInfo = {value:indent} else indentInfo = {}
    pieces = []; str = '"'
    while char
      if char=='"'
        if str!='"' then pieces.push str+'"'; char = text[++cursor]
        return {type: INTERPOLATE_STRING, value: ['string!'].concat(pieces), atom:true
        cursor:cur, stopCursor:cursor,
        line:line, stopLine: lineno}
      else if char=='\n'
        if not concatenating then str += char
        char = text[++cursor]
        if char=='\r'
          if not concatenating then str += char
          char = text[++cursor]
        concatenating = false
        while 1
          lineno++
          while char==' ' then str += char; char = text[++cursor]
          if char=='\n'
            str += char; char = text[++cursor]
            if char=='\r' then str += char; char = text[++cursor]
            continue
          else if char=='\r'
            str += char; char = text[++cursor]
            if char=='\n' then str += char; char = text[++cursor]
            continue
          else break
        column = cursor-lineStart
        if char=='\t' then error 'unexpected tab character "\t" in the head of line'
        else if indentInfo.value==undefined then indentInfo.value = column
        else
          ind = indentInfo.value
          if ind>column then i = 0; n = column-ind; while i++<n then result += ' '
          else if ind<column then error 'expect equal to or more than the indent of first line of the string'
      else if char=='\r'
        if not concatenating then str += char
        char = text[++cursor]
        if char=='\n'
          if not concatenating then str += char
          char = text[++cursor]
        concatenating = false
        while 1
          lineno++
          while char==' ' then str += char; char = text[++cursor]
          if char=='\n'
            str += char; char = text[++cursor]
            if char=='\r' then str += char; char = text[++cursor]
            continue
          else if char=='\r'
            str += char; char = text[++cursor]
            if char=='\n' then str += char; char = text[++cursor]
            continue
          else break
        column = cursor-lineStart
        if char=='\t' then error 'unexpected tab character "\t" in the head of line'
        else if indentInfo.value==undefined then indentInfo.value = column
        else
          ind = indentInfo.value
          if ind>column then i = 0; n = column-ind; while i++<n then result += ' '
          else if ind<column then error 'expect equal to or more than the indent of first line of the string'
      else if char=='$'
        literalStart = ++cursor; char = text[cursor]
        if not firstIdentifierCharSet[char] then str += '$'
        else
          x = parser.interpolateExpression()
          if text[cursor]==':'
            char = text[++cursor]
            pieces.push str+text[literalStart...cursor]+'"'; str = '"'
          else if str!='"' then pieces.push str+'"'; str = '"'
          pieces.push x
      else if char=='(' or char=='{' or char=='['
        # for efficiency, do not match next token while matching delimiter token (...), [...], {...} in tokenOnLeftParenChar, tokenOnLeftBracketChar, tokenOnLeftCurveChar
        pieces.push str+char+'"'; str = '"'
        matchToken()
        pieces.push token
        str = '"'+text[cursor-1]
      else if char=='\\'
        if not (char=text[++cursor]) then break
        else if char=='\n' or char=='\r' then char = text[++cursor]; concatenating = true
        else str += '\\'+char; char = text[++cursor]
      else str += char; char = text[++cursor]
    if not text[cursor] then error 'expect \'"\', but meet end of input while parsing interpolated string'

  # for efficiency, in tokenOnLeftParenChar, tokenOnLeftBracketChar, tokenOnLeftCurveChar
  # do not match next token while matching delimiter token (...), [...], {...}
  tokenFnMap['('] = tokenOnLeftParenChar = ->
    cur = cursor; line = lineno; column = cursor-lineStart; char = text[++cursor] # skip "("
    start = token; matchToken()
    if (parenVariantFn=parenVariantMap[token.value])
      token = parenVariantFn(); token.cursor = cursor; token.line = line; token.column = column; token.indent = lexIndent
    else
      if (type=token.type)==UNDENT then error 'unexpected undent while parsing parenethis "(...)"'
      ind = indent = lexIndent
      if type==SPACE or type==NEWLINE or type==INDENT then matchToken()
      if token.value==')'
        token = {type: PAREN, value:[], atom:true, cursor:cur, stopCursor: cursor, line:lineno, column:column, indent:lexIndent, empty:true }
        start.next = token
        return token
      exp = parser.operatorExpression()
      if token.type==UNDENT
        if token.indent<ind then error 'expect ) indent equal to or more than ('
        else matchToken()
      else if token.value!=')' then error 'expect )'
      #else matchToken() # do not match token here, so token.next==undefined, and nextToken() will matchToken instead.
      exp.type = PAREN; exp.cursor = cur; exp.stopCursor = cursor
      exp.line = line; exp.column = column; exp.indent = lexIndent
      exp.atom = true
      token = exp
    start.next = token

  parenVariantMap = {
  }

  tokenFnMap['['] = tokenOnLeftBracketChar = ->
    cur = cursor; char = text[++cursor]; line = lineno; column = cursor-lineStart
    start = token; matchToken()
    if (bracketVariantFn=bracketVariantMap[token.value])
      token = bracketVariantFn(); token.cursor = cursor; token.line = lineno; token.column = column; token.indent = indent
    else
      expList = parser.lineBlock()
      if token.type==UNDENT
        if token.indent<ind then error 'unexpected undent while parsing parenethis "[...]"'
        else matchToken()
      if token.value!=']' then error 'expect ]'
      if expList then expList.unshift 'list!'
      else expList = []
      token = {type: BRACKET, value:expList, cursor:cur, stopCursor: cursor, line:line, column:column, indent:lexIndent}
    start.next = token; token.atom = true
    token

  bracketVariantMap = {}

  tokenFnMap['{'] = ->
    cur = cursor; char = text[++cursor]; line = lineno; column = cursor-lineStart
    start = token; matchToken()
    if (curveVariantFn=curveVariantMap[token.value])
      token = curveVariantFn()
      token.cursor = cur; token.stopCursor = cursor; token.line = line; token.stopLine = lineno; token.column = column
      token.indent = lexIndent
      return token
    else
      if token.value=='}' and matchToken()
        token = {value:text[cur...cursor], value:['hash!'], cursor:cur, line:line, column:column, indent:lexIndent}
        start.next = token
        return start
      body = parser.lineBlock()
      if token.type==UNDENT and token.indent<ind then nextToken()
      if token.value!='}' then error 'expect }' else cursor++
      if indent<ind then error 'unexpected undent while parsing parenethis "{...}"'
      if body.length==0 then return {type: CURVE, value:'', cursor:cur, stopCursor:cursor, line:line, column:column, indent:lexIndent}
      if body.length==1 then body = body[0]
      else body.unshift 'begin!'
    {type: CURVE, value:body, atom:true, cursor:cur, stopCursor:cursor, line:line, column:column, indent:lexIndent}

  curveVariantMap =
    '.': ->  matchToken(); return parser.hash()

  @hash = ->
    start = token; ind = indent
    if token.type==SPACE
      if token.stopLine==token.line
        matchToken()
        items = hashLineBlock(ind)
      else items = hashBlock(ind)
    else if token.type==INDENT
      matchToken()
      items = parser.hashBlock(ind)
    else items = hashLineBlock(ind)
    if token.type==UNDENT then matchToken()
    if token.indent<ind then error "expect the same indent as or more indent as the start line of hash block"
    if token.value!='}' then error 'expect }'
    matchToken()
    extendSyntaxInfo {value:['hash!'].concat(items), atom:true}, start, token

  hashLineBlock = (dent) ->
    items = hashLine(dent)
    items.push.apply items, hashBlock(indent)
    items

  hashLine = ->
    result = []
    while (x=parser.hashItem())
      result.push x
      if (value=token.value)==';' then matchToken(); if token.type==SPACE then matchToken()
      else if (type=token.type)==NEWLINE then matchToken(); break
      else if type==UNDENT or value=='}' then break
      else if type==EOI then error "unexpected end of input while parsing hash block"
    return result

  hashBlock = ->
    start = token; result = []
    while (items=hashLine())
      result.push.apply result, items
      if (type=token.type)==EOI then error "unexpected end of input while parsing hash block"
      else if type==UNDENT then break
      else if (value=token.value)==';' then matchToken()
      else if value=='}' then break
      if token.type==INDENT
        if token.isComment
          blk = parser.hashBlock()
          result.push.apply result, blk
        else error "unexpected indent while parsing hash block"
    result.start = start; result.stop = token; result

  @hashItem = hashItem = ->
    if token.type==UNDENT then return
    start = token
    if key=parser.compactClauseExpression()
      if (type=token.type)==NEWLINE or type==UNDENT then error 'unexpected new line after hash key'
      else if type==EOI then "unexpected end of input after hash key"
      else if type==SPACE then matchToken()
      if (value=token.value)==':' and matchToken()
        if (t=key.type)==IDENTIFIER or t==NUMBER or t==NON_INTERPOLATE_STRING then js = true
      else if value=='=>' then matchToken()
      else error 'expect : or => for hash item definition'
      if token.type==SPACE then matchToken()
      value = parser.clause()
      if not value then error 'expect value of hash item'
      if js then result = ['jshashitem!', key, value]
      else result = ['pyhashitem!', key, value]
      extendSyntaxInfo result, start, token

  tokenOnRightDelimiterChar = ->
    c = char; cur = cursor; char = text[++cursor]
    token.next = {type:RIGHT_DELIMITER, value:c, cursor:cur, stopCursor:cursor,
    line:lineno, column:cur-lineStart}

  for c in ')]}' then tokenFnMap[c] = tokenOnRightDelimiterChar

  @followMatch = followMatch = (fn) ->
    cur = cursor; line = lineno
    x = fn()
    cursor = cur; lineno = line
    x

  @follow = follow = (matcherName) ->
    cur = cursor; line = lineno
    x = parser[matcherName]()
    cursor = cur; lineno = line
    x

  @expect = expect = (matcherName, message) ->
    if not (x = parser[matcherName]()) then error message
    else x

  @followSequence = followSequence = (matcherList...) ->
    cur = cursor; line1 = lineno
    for matcherName in  matcherList
      if not (x=parser[matcherName]()) then break
    cursor = cur; lineno = line1
    x

  @followOneOf = (matcherList...) ->
    cur = cursor; line1 = lineno
    for matcherName in  matcherList
      cursor = cur; lineno = line1 # defensive coding style
      if x =  parser[matcherName]() then break
    cursor = cur; lineno = line1
    x

  @setText = (x) -> parser.text = text = x; x
  @cursor = -> cursor
  @setCursor = (x) -> cursor = x
  @atStatementHead = -> atStatementHead
  @setAtStatementHead = (x) -> atStatementHead = x
  @endOfInput = -> not text[cursor]

  spaces = ->
    cur = cursor
    while char==' ' or char=='\t' then char = text[++cursor]
    {value:text[cur...cursor]}

  # c should not be \n \r
  matchChar = (c) -> if char==c then char = text[++cursor]; true

  @literal = literal = (string) ->
    length = string.length
    if text[cursor...cursor+length]==string then cursor += length; char = text[cursor]; true

  @decimal = decimal = ->
    cur = cursor
    while '0'<=char<='9' then char = text[++cursor]
    if cursor==cur then return
    {value: text[cur...cursor], cursor:cur}

  @symbolOrIdentifier = -> parser.symbol() or parser.identifier()

  # prefix operator don't need to be compared to current global priority
  @prefixOperator = (mode) ->
    # hasOwnProperty.call is necessary in order to avoid error while builtin attribute of object is defined prefix operator
    tokenText = token.value
    if not hasOwnProperty.call(prefixOperatorDict, tokenText) or  not (op=prefixOperatorDict[tokenText]) then return
    if token.escaped then return
    opToken = token; nextToken()
    if token.value=='.' and nextToken()
      if (type=token.type)==SPACE or type==INDENT or type==UNDENT or type==NEWLINE
        if mode==OPERATOR_EXPRESSION then error 'unexpected spaces after :'
        else token = opToken; return
    else if (type=token.type)==INDENT then error 'unexpected indent after prefix operator'
    else if type==NEWLINE then error 'unexpected new line after prefix operator'
    else if type==UNDENT then error 'unexpected undent after prefix operator'
    else if (tokenText=token.value)==")" or tokenText==']' or tokenText=="}" then error 'unexpected '+tokenText+' after prefix operator'
    else if type==SPACE then matchToken(); priInc = 300
    else priInc = 600
    opToken.symbol = op.symbol; opToken.priority = op.priority+priInc
    extendSyntaxInfo opToken, opToken

  # suffix operator must be symbol, should follow space, right delimiters or punctuations.
  @suffixOperator = (mode, x) ->
    if token.type!=SYMBOL then return
    if (op=suffixOperatorDict[token.value])
      token.symbol = op.symbol; token.priority = op.priority+600
      opToken = token; matchToken()
      #  can not follow suffirx: SYMBOL IDENTIFIER  REGEXP PAREN BRACKET HASH etc
      if (type=token.type)==SPACE or type==NEWLINE or type==INDENT or type==UNDENT or type==EOI or type==RIGHT_DELIMITER\
          or (value=token.value)==':' or value==',' or value==';'
        extendSyntaxInfo opToken, opToken
      else token = opToken; return

  binaryOperatorMemoIndex = memoIndex
  memoIndex += 5

  @binaryOperator = (mode, x) ->
    if m=token[binaryOperatorMemoIndex+mode] then token = m.next or token; return m.result
    start = token
    switch type1=token.type
      when EOI, RIGHT_DELIMITER then token[binaryOperatorMemoIndex+mode] = {}; return
      when NEWLINE then priInc = 0; nextToken()
      when UNDENT
        if mode!=OPERATOR_EXPRESSION then token[binaryOperatorMemoIndex+mode] = {}; return
        else priInc = 0; nextToken()
      when INDENT
        if mode!=OPERATOR_EXPRESSION and mode!=INDENT_EXPRESSION
          token[binaryOperatorMemoIndex+mode] = {}; return
        else priInc = 0; nextToken()
      when SPACE
        if mode==COMPACT_CLAUSE_EXPRESSION then token[binaryOperatorMemoIndex+mode] = {}; return
        else
          start = token; nextToken()
          if token.value=='.'
            if nextToken() and token.type==SPACE and nextToken()
              return {symbol:'attribute!', type: SYMBOL, priority: 800, start:start}
            else token[binaryOperatorMemoIndex+mode] = {}; token = start; return
          else priInc = 300
      when PUNCTUATION
        if mode!=OPERATOR_EXPRESSION and mode!=INDENT_EXPRESSION
          token[binaryOperatorMemoIndex+mode] = {}; return
        else priInc = 600
      when PAREN
        return  {symbol:'call()', type: SYMBOL, priority: 800, start:token}
      when BRACKET then return {symbol:'index[]', type: SYMBOL, priority: 800, start:token}
      when IDENTIFIER
        cur = token.cursor
        if (x.value=='@' and x.stopCursor==cur) or (text[cur-2...cur]=='::' and text[cur-3]!=':')
          return {symbol:'attribute!', type: SYMBOL, priority: 800, start:token}
        else start[binaryOperatorMemoIndex+mode] = {}; return
      when SYMBOL
        tkn = token
        if (value=tkn.value)=='#' and nextToken() then return {symbol:'#()', type: SYMBOL, priority: 800, start:tkn}
        else if value=='::' then return {symbol:'attribute!', type: SYMBOL, start:tkn, priority: 800}
        else if value=="." and (tkn=token) and nextToken()
          if (type=token.type)==IDENTIFIER then return {symbol:'attribute!', type: SYMBOL, start:tkn, priority: 800}
          else if type==SPACE or type==NEWLINE or type==INDENT or type==UNDENT or type==EOI
            if mode==OPERATOR_EXPRESSION then error 'unexpected space or new line or end of line after "."'
            else token = tkn; return
          else if type==NUMBER or type==NON_INTERPOLATE_STRING or type==INTERPOLATE_STRING
            return {symbol:'index!', type: SYMBOL, start:tkn, priority: 800}
          else priInc = 600
        else priInc = 600
      else priInc = 600
    opValue = token.value
    if not hasOwnProperty.call(binaryOperatorDict, opValue) or not (op=binaryOperatorDict[opValue])
      start[binaryOperatorMemoIndex+mode] = {}
      token = start; return
    opToken = token; nextToken()

    if token.value=='.'
      if priInc==300 then error 'unexpected "." after binary operator '+opToken.value+', here should be spaces, comment or newline'
      else nextToken()

    switch token.type
      when SPACE
        if priInc==600
          if opValue==',' then priInc = 300; nextToken()
          else error 'unexpected spaces or new lines after binary operator "'+opValue+'" before which there is no space.'
        else if priInc==300 then nextToken()
        else
          nextToken()
          if type1==INDENT then indentExpression()
      when NEWLINE
        if opValue!=',' then error 'unexpected new line after binary operator '+opValue
        else if priInc==0 then error 'a single binary operator should not occupy whole line.'
        else priInc = 0
      when UNDENT
        if mode!=OPERATOR_EXPRESSION then error 'unexpected undent after binary operator '+opValue
        else return
      when INDENT
        if opValue!=',' then error 'unexpected indent after binary operator '+opValue
        priInc = 0; indentExpression()
      when EOI
        if mode!=OPERATOR_EXPRESSION then error 'unexpected end of input, expect right operand after binary operator'
      when RIGHT_DELIMITER
        if mode!=OPERATOR_EXPRESSION then  start[binaryOperatorMemoIndex+mode] = {}; return
        else error 'unexpected '+token.value
      when PUNCTUATION
        if mode!=OPERATOR_EXPRESSION then return
        else if priInc!=0 then error 'unexpected '+token.value
        if priInc==0
          if opValue==',' or opValue==':' then error 'binary operator '+op.symbol+' should not be at begin of line'
      else
        if priInc==300
          if mode==OPERATOR_EXPRESSION then error 'binary operator '+opValue+' should have spaces at its right side.'
          else token = start; start[binaryOperatorMemoIndex+mode] = {}; return
        else if priInc==0
          if opValue=='%' or op.assign then error 'binary operator '+opValue+' should not be at begin of line'
          if type1==INDENT then indentExpression()

    opToken.symbol = op.symbol; pri = op.priority+priInc
    opToken.assign = op.assign; opToken.rightAssoc = op.rightAssoc
    # any operator near newline always have the priority 300, i.e. compute from up to down
    if pri<300 then pri = 300; opToken.rightAssoc = false
    opToken.priority = pri
    start[binaryOperatorMemoIndex+OPERATOR_EXPRESSION] = {result:opToken, next:token}
    opToken

  indentExpression = ->
    indentExp = parser.expression(INDENT_EXPRESSION, 0, true)
    if (type=token.type)!=UNDENT and type!=EOI and token.value!=')'
      error 'expect an undent after a indented block expression'
    indentExp.priority = 1000
    indentExp[expressionMemoIndex+OPERATOR_EXPRESSION] = {result:indentExp, next:token}
    token = indentExp

  @prefixExpression = (mode, priority) ->
    # current global prority doesn't affect prefixOperator
    if op=parser.prefixOperator(mode)
      pri = if priority>op.priority then priority else op.priority
      x = parser.expression(mode, pri, true)
      if x then extendSyntaxInfo makeExpression(PREFIX, op, x)

  expressionMemoIndex = memoIndex
  memoIndex += 5
  @expression = expression = (mode, priority, leftAssoc) ->
    indexMode = expressionMemoIndex+mode; start = token
    if m=start[indexMode] then token = m.next or token; return m.result
    if not x = parser.prefixExpression(mode, priority)
      if not token.atom then start[memoIndex+mode] = {}; return
      else x = token; x.priority = 1000; x.start = x; nextToken()
    while 1
      tkn1 = token
      if (op = parser.suffixOperator(mode, x))
        if op.priority>=priority
          x = makeExpression(SUFFIX, op, x)
        else token = tkn1; break
      else break
    # the priority and association of suffix operator does not affect the following expression
    while 1
      tkn2 = token
      if (op=parser.binaryOperator(mode, x))
        if (opPri=op.priority)>priority  or (opPri==priority and not leftAssoc)
          # should assure that a right operand is here while parsing binary operator
          y = expression(mode, opPri, not op.rightAssoc)
          if y then x = makeExpression(BINARY, op, x, y)
          else token = tkn2; break
        else token = tkn2; break
      else break
    if token!=tkn1
      while 1
        tkn = token
        if (op = parser.suffixOperator(mode, x))
          if op.priority>=priority
            x = makeExpression(SUFFIX, op, x)
          else token = tkn; break
        else break
    start[indexMode] = {result:x, next:token}
    x

  # the priority of operator vary from 0 to 300,
  # if there is no space between them, then add 600, if there is spaces, then add 300.
  # if meet newline, add 0.
  @operatorExpression = operatorExpression = -> parser.expression(OPERATOR_EXPRESSION, 0, true)

  # compact expression as clause item.
  @compactClauseExpression = ->
    result = parser.expression(COMPACT_CLAUSE_EXPRESSION, 600, true)
    if result then result.atom = true
    result

  # space expression as clause item.
  @spaceClauseExpression = spaceClauseExpression = ->
    if token.type==SPACE then nextToken()
    parser.expression(SPACE_CLAUSE_EXPRESSION, 300, true)

  # interpolate expression embedded in string
  @interpolateExpression = ->
    exp = tokenOnIdentifierChar()
    exp.start = exp.stop = start = exp
    while 1
      cur = cursor
      if (char=text[cursor])=='.'
        if char=text[++cursor] and firstIdentifierCharSet[char] and (id=tokenOnIdentifierChar())
          exp = ['attribute!', exp, id]
          id.start = id; id.stop = id; exp.start = start; exp.stop = id
        else break
      else if char=='['
        if (tkn=tokenOnLeftBracketChar()) and token.type==BRACKET
          exp = ['index!', exp, tkn]
          exp.start = start; exp.stop = tkn
        else error 'error while parsing "[" leading interpolate expression in double qoute string'
      else cursor = cur; break
    exp

  @isIdentifier = isIdentifier = (item) -> item.type==IDENTIFIER

  @itemToParameter = itemToParameter = (item) ->
    if item.type==IDENTIFIER then return item
    else if item0=item[0]
      if item0=='attribute!' and item[1].text=='@' then return item
      else if item0.symbol=='x...'
        parser.meetEllipsis = item[1].ellipsis = true
        return item
      else if entity(item0)=='=' # default parameter
        # default parameter should not be ellipsis parameter at the same time
        # and this is the behavior in coffee-script too
        # and (item01[0].symbol!='x...' or not isIdentifier(item01[1]).type==IDENTIFIER)
        if (item1=item[1]) and item1.type==IDENTIFIER then return item
        else if ((item10=item1[0]) and item10=='attribute!' and item1[1].text=='@') then return item
        else return
      # for dynamic parser and writing macro
      else if item0.symbol=='unquote!' or item0.symbol=='unquote-splice'
        return item

  @toParameters = toParameters = (item) ->
    if not item then return []
    if x=itemToParameter(item) then return [x]
    else if item[0]==','
      result = for x in item[1...]
        if not(param=itemToParameter(x)) then meetError = true; break
        if param.ellipsis
          if meetEllipsis then meetError = true; break
          else meetEllipsis = true
        param
      if not meetError then result

  @labelStatement = ->
    start = cursor; line1 = lineno
    if not (lbl=parser.jsIdentifier()) then return
    if text[cursor]!='#' then cursor = start; return
    cursor++
    if (spac=bigSpace()) and (not spac.text or spac.undent or spac.newline)  then cursor = start; return
    if clause=parser.clause() then clause = ['label!', lbl, clause]
    else clause = ['label!', lbl, '']
    extendSyntaxInfo clause, start, token

  @conjunction = ->
    start = cursor
    if (x=symbol() or taijiIdentifier()) and isConjunction(x) then return x
    cursor = start; return

  @expectIndentConj = expectIndentConj = (word, line1, isHeadStatement, options, clauseFn) ->
    start2 = cursor; line2 = lineno
    if options.optionalClause? then optionalClause = options.optionalClause
    else optionalClause = word!='then'
    if options.optionalWord? then optionalWord = options.optionalWord
    else optionalWord = word=='then'
    indentCol = lineInfo[line1].indentCol
    spac = bigSpace(); column = lineInfo[lineno].indentCol
    if column==indentCol and lineno!=line1 and not isHeadStatement
      if not optionalClause
        error 'meet new line, expect inline keyword "'+word+'" for inline statement'
      else rollbackToken spac; return
    if column<indentCol
      if not optionalClause then error 'unexpected undent, expect '+word
      else rollbackToken spac; return
    else if column>indentCol
      if options.indentCol
        if column!=options.indentCol then error 'unconsistent indent'
      else options.indentCol = column
    w = taijiIdentifier()
    meetWord = w and w.text==word
    if not meetWord
      if isConjunction(w)
        if optionalClause then rollbackToken spac; return
        else  error 'unexpected '+w.text+', expect '+word+' clause'
      else if (not optionalWord and not optionalClause) or (
          not optionalClause and optionalWord and spac.inline)
        if word!='then' or not options.colonAtEndOfLine then error 'expect keyword '+word
      else if not optionalWord then return rollbackToken spac
      else if optionalClause then return rollbackToken spac
    if not meetWord then rollback start2, line2
    clauseFn()

  conjClause = (conj, line1, isHeadStatement, options) ->
    begin(expectIndentConj conj, line1, isHeadStatement, options, parser.lineBlock)

  thenClause  = (line1, isHeadStatement, options) -> conjClause 'then', line1, isHeadStatement, options
  elseClause  = (line1, isHeadStatement, options) -> conjClause 'else', line1, isHeadStatement, options
  finallyClause  = (line1, isHeadStatement, options) -> conjClause 'finally', line1, isHeadStatement, options
  catchClause = (line1, isHeadStatement, options) ->
    expectIndentConj 'catch', line1, isHeadStatement, options, ->
      line2 = lineno; space(); atStatementHead = false
      catchVar = parser.identifier(); space(); then_ = thenClause(line2, false, {})
      [catchVar, then_]

  caseClauseOfSwitchStatement = (line1, isHeadStatement, options) ->
    expectIndentConj 'case', line1, isHeadStatement, options, ->
      line2 = lineno; space(); atStatementHead = false
      exp = parser.compactClauseExpression()
      #if exp.isBracket then exp.shift()
      if exp[0]!='list!' then exp = ['list!', exp]
      space(); expectChar(':', 'expect ":" after case values')
      body = parser.block() or parser.lineBlock()
      [exp, begin(body)]

  @keyword = ->
    start = cursor
    if (x=symbol() or taijiIdentifier()) and isKeyword(x) then return x
    cursor = start; return

  # if test then action else action
  keywordThenElseStatement = (keyword) -> (isHeadStatement) ->
    line1 = lineno; space()
    if not (test=parser.clause())? then error 'expect a clause after "'+keyword+'"'
    then_ = thenClause(line1, isHeadStatement, options={colonAtEndOfLine: test.colonAtEndOfLine})
    else_ = elseClause(line1, isHeadStatement, options)
    if else_ then [keyword, test, then_, else_]
    else [keyword, test, then_]

  # while! test body...
  keywordTestExpressionBodyStatement = (keyword) -> (isHeadStatement) ->
    line1 = lineno; space()
    if not (test = parser.compactClauseExpression())
      error 'expect a compact clause expression after "'+keyword+'"'
    if not (body = parser.lineBlock()) then error 'expect the body for while! statement'
    [keyword, test, begin(body)]

  # throw or return value
  throwReturnStatement = (keyword) -> (isHeadStatement) ->
    space(); if text[cursor]==':' and text[cursor+1]!=':' then cursor++; space();
    if clause = parser.clause() then [keyword, clause] else [keyword]

  # break; continue
  breakContinueStatement = (keyword) -> (isHeadStatement) ->
    space()
    if lbl = jsIdentifier() then [keyword, lbl] else [keyword]

  letLikeStatement = (keyword) -> (isHeadStatement) ->
    line1 = lineno; space()
    varDesc = parser.varInitList() or parser.clause()
    [keyword, varDesc, thenClause(line1, isHeadStatement, {})]

  # no cursor and lineno is attached in result, so can not be memorized directly.
  @identifierLine = ->
    result = []
    while space() and not parser.lineEnd() and not follow('newline') and text[cursor]!=';'
      if x=parser.identifier() then result.push x
      else error 'expect an identifier'
    result

  # no cursor and lineno is attached in result, so can not be memorized directly.
  @identifierList = ->
    line1 = lineno; indentCol = lineInfo[line1].indentCol
    result = parser.identifierLine()
    spac = bigSpace();
    if (col0=lineInfo[lineno].indentCol)<=indentCol
      rollbackToken spac; return result
    if text[cursor]==';' then return result
    while varList=parser.identifierLine()
      result.push.apply result, varList
      spac = bigSpace()
      if (column=lineInfo[lineno].indentCol)<=indentCol then rollbackToken spac; break
      else if column!=col0 then error 'inconsistent indent of multiple identifiers lines after extern!'
      if text[cursor]==';' then break
    result

  @varInit = ->
    if not (id = parser.identifier()) then return
    space()
    if text[cursor]=='=' and cursor++
      if value=parser.block() then value = begin(value)
      else if not(value=parser.clause()) then error 'expect a value after "=" in variable initilization'
    space()
    if text[cursor]==',' then cursor++
    if not value then return id else return [id, '=', value]

  @varInitList = ->
    start = cursor; line1 = lineno; result = []
    indentCol0 = lineInfo[lineno].indentCol
    spac = bigSpace()
    column = lineInfo[lineno].indentCol
    if column>indentCol0 then indentCol1 = column
    else if spac.undent or spac.newline then error 'unexpected new line, expect at least one variable in var statement'
    while 1
      if x=parser.varInit() then result.push x
      else break
      space1 = bigSpace()
      column = lineInfo[lineno].indentCol
      if not text[cursor] or text[cursor]==';' or follow 'rightDelimiter' then break
      if lineno==line1 then continue
      if column>indentCol0
        if indentCol1 and column!=indentCol1 then error 'unconsitent indent in var initialization block'
        else if not indentCol1 then indentCol1 = column
      else if column==indentCol0 then break
      else rollbackToken space1
    # if not result.length then error 'expect at least one variable in var statement'
    if not result.length then rollback start, line1; return
    return result

  @importItem = ->
    start = cursor; line1 = lineno
    sym = parser.symbol()
    if sym and (symValue=sym.text)!='#' and symValue!='#/'
      error 'unexpected symbol after "as" in import! statement'
    name = parser.identifier()
    if name
      if name.text=='from'
        if sym
          error 'keyword "from" should not follow "#" or "#/" immediately in import! statement, expect variable name instead'
        else return rollback(start, lineno)
    else if text[cursor]=="'" or text[cursor]=='"'
      if sym
        error 'file path should not follow "#" or "#/" immediately in import! statement, expect variable name instead'
      else return  rollback(start, lineno)
    space()
    start1 = cursor; line2 = lineno
    if (as_=taijiIdentifier())
      if as_.text=='from' then as_ = undefined; rollback start1, line2
      else if as_.text!='as' then error 'unexpected word '+as_.text+', expect "as", "," or "from [module path...]"'
      else
        space()
        sym2 = parser.symbol()
        if sym2 and (symValue2=sym2.text)!='#' and symValue2!='#/'
          error 'unexpected symbol after "as" in import! statement'
        if symValue=='#/'
          if symValue2=='#'
            error 'expect "as #/alias" or or "as alias #alias2" after "#/'+name.text+'"'
        else if symValue=='#'
          if not symValue
            error 'meta variable can not be imported as runtime variable'
          else if symValue=='#/'
            error 'meta variable can not be imported as both meta and runtime variable'
        else if not symValue
          if symValue2=='#'
            error 'runtime variable can not be imported as meta variable'
          else if symValue2=='#/'
            'runtime variable can not be imported as both meta and runtime variable'
        space(); asName = expectIdentifier()
        if symValue=='#/' and not symValue2
          space(); sym3 = parser.symbol()
          if not sym3 then error 'expect # after "#/'+name.text+' as '+asName.text+'"'
          else if sym3.text!='#' then error 'unexpected '+sym3.text+' after "#/'+name.text+'as '+asName.text+'"'
          asName2 = expectIdentifier()
    if not as_
      if symValue=='#/' then return [[name, name], [name, name, 'meta']]
      else if symValue=='#' then return [[name, name, 'meta']]
      else return [[name, name]]
    else
      if symValue=='#/'
        if asName2 then return [[name, asName], [name,asName2, 'meta']]
        else return [[name, asName], [name,asName, 'meta']]
      else if symValue=='#' then return [[name, asName, 'meta']]
      else return [[name, asName]]

  @exportItem = ->
    runtime = undefined
    if text[cursor...cursor+2]=='#/' then cursor+=2; runtime = 'runtime'; meta = 'meta'; space()
    else if (c=text[cursor])=='#' then cursor++; meta = 'meta'; space()
    else runtime = 'runtime'
    if meta then name = expectIdentifier()
    else if not (name = taijiIdentifier()) then return
    space()
    if text[cursor]=='=' and cursor++
      space(); value = parser.spaceClauseExpression(); space()
    [name, value, runtime, meta]

  @spaceComma = spaceComma = -> space(); if text[cursor]==',' then cursor++; space(); return true
  @seperatorList = seperatorList = (item, seperator) ->
    if typeof item=='string' then item = parser[item]
    ->
      result = []
      while x=item()
        result.push x
        if seperator() then continue
        else break
      result

  @importItemList = seperatorList('importItem', spaceComma)

  @exportItemList = seperatorList('exportItem', spaceComma)

  @expectIdentifier = expectIdentifier = (message) ->
    if id=parser.identifier() then return id
    else error message or 'expect identifier'

  @expectOneOfWords = expectOneOfWords = (words...) ->
    space(); token = taijiIdentifier();
    if not token then error 'expect one of the words: '+words.join(' ')
    value = token.value; i = 0; length = words.length;
    while i<length then (if value==words[i] then return words[i] else i++)
    error 'expect one of the words: '+words.join(' ')

  maybeOneOfWords = (words...) ->
    space(); token = taijiIdentifier();
    if not token then return
    value = token.value; i = 0; length = words.length;
    while i<length then (if value==words[i] then return words[i] else i++)
    return
  expectWord = (word) -> space(); (if not (token=taijiIdentifier()) or token.value!=word then error 'expect '+ word); word
  word = (w) ->
    start = cursor; line1 = lineno; space()
    if not token=taijiIdentifier() then return
    if token.value!=w then return rollback(start, line1)
    return token

  @expectChar = expectChar = (c) -> if text[cursor]==c then cursor++ else error 'expect "'+c+'"'

  @endOfDynamicBlock = @eob = ->
    if cursor==endCursorOfDynamicBlockStack[-1] then return true
    else return false

  @keywordToStatementMap =
    '%': (isHeadStatement) ->
      start = cursor; line1 = lineno
      if not space().text then return
      leadClause = parser.clause()
      code = compileExp(['return', ['%/', leadClause]], environment)
      space(); indentCol = lineInfo[lineno].indentCol
      if expectWord('then') or (text[cursor]==':' and cursor++)
        space()
        if newline()
          blockStopLineno = lineno
          while lineInfo[blockStopLineno].indentCol>indentCol and blockStopLineno<maxLine
            blockStopLineno++
          cursorAtEndOfDynamicBlock = lineInfo[blockStopLineno].indentCol or text.length
        else
          blockStopLineno = lineno+1
          cursorAtEndOfDynamicBlock = lineInfo[blockStopLineno].indentCol or text.length
      else error 'expect "then" or ":"'
      endCursorOfDynamicBlockStack.push cursorAtEndOfDynamicBlock
      result = new Function('__$taiji_$_$parser__', code)(parser)
      endCursorOfDynamicBlockStack.pop()
      cursor = cursorAtEndOfDynamicBlock; lineno = blockStopLineno
      extendSyntaxInfo result, start, token

    'break': breakContinueStatement('break')
    'continue': breakContinueStatement('continue')
    'throw': throwReturnStatement('throw')
    'return': throwReturnStatement('return')
    'new': throwReturnStatement('new')

    'var': (isHeadStatement) -> ['var'].concat parser.varInitList()
    'extern!': (isHeadStatement) -> ['extern!'].concat parser.identifierList()
    'include!': (isHeadStatement) ->
      space(); filePath = expect('string', 'expect a file path')
      space()
      if word('by')
        space(); parseMethod = expect('taijiIdentifier', 'expect a parser method')
      ['include!', filePath, parseMethod]

    # import [#/]name [as [#/]name] ... from path as [#/]name #name [by method]
    'import!': (isHeadStatement) ->
      space()
      items = parser.importItemList(); space()
      if items.length then from_ = expectWord('from') # or items[0][2]
      else from_ = word('from')
      #if not from_ then return ['import!', names[0][0], names[0][1], []]
      space(); srcModule = parser.string(); space();
      if as_ = literal('as')
        space()
        sym = parser.symbol()
        if sym
          if (symValue=sym.text)!='#' and sym.text!='#/'
            error 'unexpected symbol before import module name', sym
        alias = expectIdentifier('expect an alias for module')
        if symValue=='#' then metaAlias = alias; alias = undefined
        else if symValue=='#/' then metaAlias = alias
        space()
        sym2 = parser.symbol()
        if sym and sym2 then error 'unexpected symbol after meta alias'
        space(); alias2 = parser.identifier()
        # sym is the first symbol # or #/
        if sym  and alias2 then 'unexpected identifier '+alias2+' after '+symValue+alias
        if alias2 then metaAlias = alias2
        space()
      if word('by')
        space(); parseMethod = expect('taijiIdentifier', 'expect a parser method')
      runtimeImportList = []; metaImportList = []
      for item in items
        for x in item
          if x[2] then  metaImportList.push x
          else runtimeImportList.push x
      ['import!'].concat [srcModule, parseMethod, alias, metaAlias, runtimeImportList, metaImportList]

    'export!': (isHeadStatement) -> space(); ['export!'].concat parser.exportItemList()

    'let': letLikeStatement('let')
    'letrec!': letLikeStatement('letrec!')
    'letloop!': letLikeStatement('letloop!')
    'if': keywordThenElseStatement('if')
    'while': keywordThenElseStatement('while')
    'while!': keywordTestExpressionBodyStatement('while!')

    'for': (isHeadStatement) ->
      line1 = lineno; space()
      if text[cursor]=='(' and cursor++
        init = parser.clause(); space(); expectChar(';')
        test = parser.clause(); space(); expectChar(';')
        step = parser.clause(); space(); expectChar(')')
        return ['cFor!', init, test, step, thenClause(line1, isHeadStatement, {})]
      name1 = expectIdentifier(); space()
      if text[cursor]==',' then cursor++; space()
      if (token=jsIdentifier()) and value=token.value
        if value=='in' or value=='of' then inOf = value
        else name2 = value; space(); inOf = expectOneOfWords('in', 'of')
        space(); obj = parser.clause()
      if name2
        if inOf=='in' then kw = 'forIn!!' else kw = 'forOf!!'
        [kw, name1, name2, obj, thenClause(line1, isHeadStatement, {})]
      else
        if inOf=='in' then kw = 'forIn!' else kw = 'forOf!'
        [kw, name1, obj, thenClause(line1, isHeadStatement, {})]

    'do': (isHeadStatement) ->
      line1 = lineno; space(); indentCol = lineInfo[lineno].indentCol
      body = parser.lineBlock()
      if newlineFromLine(line1, lineno) and not isHeadStatement then return body
      if not (conj=maybeOneOfWords('where', 'when', 'until'))
        error 'expect conjunction where, when or until'
      if conj=='where' then tailClause = parser.varInitList()
      else tailClause = parser.clause()
      if conj=='where' then ['let', tailClause, body]
      else if conj=='when' then ['doWhile!', body, tailClause]
      else ['doWhile!', body, ['!x', tailClause]]

    'switch': (isHeadStatement) ->
      line1 = lineno
      if not (test = parser.clause()) then error 'expect a clause after "switch"'
      options = {}; cases = ['list!']
      while case_=caseClauseOfSwitchStatement(line1, isHeadStatement, options) then cases.push case_
      else_ = elseClause(line1, isHeadStatement, options)
      ['switch', test, cases, else_]

    'try': (isHeadStatement) ->
      line1 = lineno;
      if not (test = parser.lineBlock()) then error 'expect a line or block after "try"'
      if atStatementHead and not isHeadStatement
        error 'meet unexpected new line when parsing inline try statement'
      options = {}; #catchClauses = ['list!']
      #while catch_=catchClause(line1, isHeadStatement, options) then catchClauses.push catch_
      #else_ = elseClause(line1, isHeadStatement, options);
      catch_ = catchClause(line1, isHeadStatement, options)
      if not catch_ then error 'expect a catch clause for try-catch statement'
      final = finallyClause(line1, isHeadStatement, options)
      #['try', begin(test), catch_, else_, final]
      ['try', begin(test), catch_[0], catch_[1], final]

    'class': (isHeadStatement) ->
      line1 = lineno; space();
      # class name should be provided explicitly
      name = expect('identifier', 'expect class name'); space()
      if parser.conjunction('extends') then space(); superClass = parser.identifier(); space()
      else supers = undefined
      if followNewline() and newlineFromLine(line1, line1+1) then body = undefined
      else body = parser.lineBlock()
      ['#call!', 'class', [name, superClass, body]]

  @statement = ->
    start = cursor; line1 = lineno
    if not (keyword = symbol() or taijiIdentifier()) then return
    if stmtFn = parser.keywordToStatementMap[keyword.text]
      isHeadStatement = atStatementHead; atStatementHead = false
      if stmt = stmtFn(isHeadStatement)
        return extendSyntaxInfo stmt, start, token
    return rollback start, line1

  @defaultAssignLeftSide = ->
    start = cursor; line1 = lineno
    if not (x=parser.spaceClauseExpression()) then return
    if x.type==PAREN or x.type==BRACKET or x.type==DATA_BRACKET or x.type==CURVE
      rollback start, line1; return
    if not x then  rollback start, line1; return
    if x.type==IDENTIFIER or ((e=entity(x)) and (e[0]=='attribute!' or e[0]=='index!')) then x
    else if x.text=='::' then x
    else if parser.isAssign(x[0]) then rollback x[1].stop, x[1].line; return x[1]
    else  rollback start, line1; return

  @isAssign = (val) -> (op=binaryOperatorDict[val]) and op.assign

  @defaultAssignSymbol = -> (x=parser.symbol()) and parser.isAssign(x.text) and x

  @defaultAssignRightSide = ->
    space2 = bigSpace()
    if space2.undent then error 'unexpected undent after assign symbol'+symbol.text
    else if space2.newline then error 'unexpected new line after assign symbol'+symbol.text
    parser.block() or parser.clause()

  @makeAssignClause = (assignLeftSide, assignSymbol, assignRightSide) -> ->
    start = cursor; line1 = lineno
    if not (left=assignLeftSide()) then return
    spac = space()
    if not (token=assignSymbol()) then return rollback start, line1
    right = assignRightSide(spac)
    if left.type==CURVE
      eLeft = entity(left)
      if typeof eLeft=='string'
        if eLeft[0]=='"' then error 'unexpected left side of assign: '+eLeft
        left = [left]
      else if eLeft and eLeft.push
        if eLeft[0]=='begin!' then error 'syntax error: left side of assign should be a list of variable names separated by space'
      else error 'unexpected left side of assign'
      return ['hashAssign!', left, right]
    extendSyntaxInfo [token, left, right], start, token

  @defaultAssignClause = @makeAssignClause @defaultAssignLeftSide, @defaultAssignSymbol, @defaultAssignRightSide

  @customAssignClauses = []

  @assignClause = ->
    for matcher in parser.customAssignClauses then if x=matcher() then return x
    parser.defaultAssignClause()

  @macroCallClause = ->
    start = cursor; line1 = lineno
    if (head=parser.compactClauseExpression())
       if (space1=space()) and not space1.text then return rollback(start, line1)
       if text[cursor]=='#' and cursor++ and ((spac=space()) and spac.text or text[cursor]=='\n' or text[cursor]=='\r')
          if blk = parser.block()
            return extendSyntaxInfo ['#call!', head, blk], start, token
          else if args = parser.clauses()
            return extendSyntaxInfo ['#call!', head, args], start, token
    rollback(start, line1)

  @parameterList = ->
    start = token
    if token.type==SPACE then nextToken()
    if token.type!=PAREN then token = start; return
    if item=token.value
      if params=parser.toParameters(item) then return params
      else
        if followSequence('inlineSpaceComment', 'defaultSymbolOfDefinition')
          error 'illegal parameters list for function definition'
        else token = start; return

  @definition = ->
    start = token
    if not (parameters=parser.parameterList()) then parameters = []
    if token.type==SPACE then nextToken()
    if (value=token.value) and ((tail=value[(value.length-2)...])=='->' or tail=='=>')
      define = token; nextToken()
      body = begin(parser.lineBlock()) or 'undefined'
      extendSyntaxInfo [define, parameters, body], start, token
    else token = start; return

  @clauseItem = ->
    if token.type==SPACE then nextToken()
    if (item=parser.compactClauseExpression())
      if item.type==PAREN  and (d=parser.definition()) then return d
      return item

  @sequenceClause = ->
    start = token; clause = []
    while item = parser.clauseItem() then clause.push item
    if not clause.length then return
    {value:clause, start:start, stop:token}

  @customClauseList = ['assignClause']

  leadTokenClause = (value) ->
    start = token
    if (type=matchToken().type)!=SPACE and type!=INDENT then token = start; return
    matchToken()
    if not (fn=leadWordClauseMap[start.value]) then token = start; return
    clause = fn(start, parser.clause())
    clause.start = start; clause.stop = token
    clause

  leadWordClauseMap =
    # eval while parsing, call by %% clause
    # e.g.
    # %% %text()
    # %% %cursor()
    # %% %number()1234
    '%%':  (tkn, clause) ->
      code = compileExp(['return', clause], environment)
      new Function('__$taiji_$_$parser__', code)(parser)

    # the head of clause will be convert to attribute of __$taiji_$_$parser__
    # see exports['%/'] and convertParserAttribute in core.coffee
    # {%/ matcheA(x, y) } will be converted to {%% %matchA(x, y)}
    '%/': (tkn, clause) ->
      # notice the difference between %% and %/
      # here ['%/', clause] is compiled
      code=compileExp(['return', [tkn, clause]], environment)
      new Function('__$taiji_$_$parser__', code)(parser)

    # identifier in clause will be convert to attribute of __$taiji_$_$parser__
    # see exports['%!'] and convertParserAttribute in core.coffee
    # {%! matcheA(x, y) } will be converted to {%% %matchA(%x, %y)}
    '%!': (tkn, clause) ->
      code=compileExp(['return', [tkn, clause]], environment)
      new Function('__$taiji_$_$parser__', code)(parser)

    '~':  (tkn, clause) -> tkn.symbol = 'quote!'; [tkn, clause]
    '`':  (tkn, clause) -> tkn.symbol = 'quasiquote!'; [tkn, clause]
    '^':  (tkn, clause) -> tkn.symbol = 'unquote!'; [tkn, clause]
    '^&': (tkn, clause) -> tkn.symbol = 'unquote-splice'; [tkn, clause]

    # preprocess opertator
    # see # see metaConvertFnMap['#'] and preprocessMetaConvertFnMap for more information
    '#':  (tkn, clause) -> [tkn, clause]

    # evaluate in compile time
    # see metaConvertFnMap['##']
    '##':  (tkn, clause) -> [tkn, clause]

    # evaluate in both compile time and run time
    # see metaConvertFnMap['#/']
    '#/': (tkn, clause) -> [tkn, clause]

    # escape from compile time to runtime
    # see metaConvertFnMap['#-']
    '#-': (tkn, clause) -> [tkn, clause]

    # #& metaConvert exp and get the current expression(not metaConverted raw program)
    # see metaConvertFnMap['#&']
    '#&': (tkn, clause) -> [tkn, clause]

  symbol2clause = {}

  for key of leadWordClauseMap then symbol2clause[key] = leadTokenClause

  @clause = ->
    start = token
    if (type=token.type)==SPACE then nextToken(); type = token.type
    if type==KEYWORD then return keyword2statement[token.value]()
    else if type==IDENTIFIER and nextToken()
      if token.value=='#' and nextToken() and token.value==':' and nextToken() and (blk=parser.lineBlock())
        # label statement
        return ['label!', start, blk]
      else token = start
    else if type==SYMBOL and (fn=symbol2clause[token.value])
      if result = fn() then return result
      else token = start

    if not (head=parser.compactClauseExpression())
      if (op=parser.prefixOperator())
        if token.type==SPACE and nextToken() and (exp=parser.spaceClauseExpression())
          return [op, exp]
        else return op
      else if token.value==',' then nextToken(); return {value:'undefined', start:start, stop:token}
      else return

    if op=parser.binaryOperator(SPACE_CLAUSE_EXPRESSION)
      originalToken = token; token = head; head.next = op
      op[binaryOperatorMemoIndex+SPACE_CLAUSE_EXPRESSION] = {result:op, next:originalToken}
      if (exp=parser.spaceClauseExpression())
        if (value=token.value)==',' then nextToken(); if token.type==SPACE then nextToken()
        else if value!=';' and (type=token.type)!=NEWLINE and type!=UNDENT and type!=EOI
          error 'after space expression clause, expect stop symbol of clause like colon, semicolon, new line, undent or end of input etc.'
        return exp
      else token = originalToken

    tkn = token
    if (exp=parser.spaceClauseExpression())
      if exp.priority<=600 and isCallable(head)
        if (value=token.value)==',' then nextToken(); if token.type==SPACE then nextToken()
        else if value!=';' and (type=token.type)!=NEWLINE and type!=UNDENT and type!=EOI
          error 'after caller leading clause, expect stop symbol of clause like colon, semicolon, new line, undent or end of input etc.'
        return [head, exp]
      else token = tkn

    else if token.value=='#' and nextToken()
      if token.type==SPACE then clauses = parser.clauses()
      else if token.type==INDENT then clauses = parser.block()
      return [head].concat clauses

    else if token.value==':'
      nextToken()
      if token.type==SPACE then nextToken()
      clause = parser.clauses()
      clause.unshift head
      return {value:clause, start:head.start, stop:token}

    if clause = parser.sequenceClause()
      clause.value.unshift head; clause.start = start
      if token.value==INDENT
        blk = parser.block()
        clause.value.push.apply clause.value, blk
        clause.stop = blk.stop
        return clause
    else clause = head

    if (value=token.value)==','
      nextToken()
      #if token.type==SPACE then nextToken()
      clause.stop = token
      clause

    else if value==':'
      # head clause with colon leading clauses or colon leading indented block
      # print: 1 + 2, 3
      # withMethod # openWindow: 100x200 400x500
      # getFn Math name:
      #   abs 1
      #   sin x
      nextToken()
      if token.type==INDENT then clauses = parser.block()
      else clauses = parser.clauses()
      clauses.unshift clause
      clauses.start = start; clauses.stop = token
      clauses

    else if token.type==INDENT
      # head clause with indented block
      # please pay attention to the difference between clause+':'+INDENT+block and clause+INDENT+block
      clauses = parser.block()
      clause.value.push.apply clause.value, clauses
      clause.stop = token
      clause

    else clause

  isCallable = (exp) -> return (type=exp.type)!=NUMBER and type!=NON_INTERPOLATE_STRING and type!=INTERPOLATE_STRING and type!=BRACKET and type!=HASH

  @clauses = ->
    result = []
    while clause=parser.clause() then result.push clause
    return result

  @lineCommentBlock = ->
    start = cursor
    if comment=parser.lineComment()
      if comment.indent
        if comment.text[...3]=='///' then result = parser.blockWithoutIndentHead(); result.unshift ['directLineComment!', comment.text]; result
        else parser.blockWithoutIndentHead()
      else
        if text[start...start+3]=='///'
          [extend(['directLineComment!', comment.text], {start:start, stop:cursor, line: lineno})]
        else [extend(['lineComment!', comment.text], {start:start, stop:cursor, line: lineno})]

  @codeCommentBlockComment = ->
    if cursor!=lineInfo[lineno].start+lineInfo[lineno].indentCol then return
    if text[cursor]!='/' then return
    if (c=text[cursor+1])=='.' or c=='/' or c=='*' then return
    start = cursor; line1 = lineno; cursor++
    code = parser.lineBlock()
    extend [['codeBlockComment!', code]], {start:start, stop:cursor, line1: line1, line: lineno}

  @sentence = ->
    start = token
    if (type=token.type)==EOI or type==UNDENT or type==RIGHT_DELIMITER or isConjunction(token)
      return
    result = parser.clauses()
    if token.value==';'
      nextToken()
      if token.type==SPACE then nextToken()
    extendSyntaxInfo result, start, token

  @line = ->
    if (type=token.type)==UNDENT or type==RIGHT_DELIMITER or isConjunction(token) and type==EOI
      return
    # if x=(parser.lineCommentBlock() or parser.codeCommentBlockComment()) then return x
    result = []
    while x = parser.sentence() then result.push.apply result, x
    if token.type==NEWLINE then nextToken()
    result

  @block = (dent) -> if token.type==INDENT then nextToken(); return parser.blockWithoutIndentHead(dent)

  # a block with out indent( the indent has been ate before).
  # stop until meet a undent (less indent than the intent of the start line)
  @blockWithoutIndentHead = (dent) ->
    result = []
    while (x=parser.line())
      result.push.apply(result, x)
      if token.indent<dent then break
    return result

  @lineBlock = (dent) ->
    if token.type==INDENT then nextToken(); parser.blockWithoutIndentHead(dent)
    else
      result = parser.line()
      if token.indent>dent
        result.push.apply result, parser.blockWithoutIndentHead()
      result

  @moduleBody = ->
    matchToken()
    if token.type==NEWLINE then matchToken()
    if token.type==SPACE then matchToken()
    body = []
    while 1
      if not x=parser.line() then break
      spac = bigSpace()
      body.push.apply body, x
      clearMemo()
      if lineInfo[lineno].indentCol<indentCol then rollbackToken spac; break
    if text[cursor] then error 'expect end of input, but meet "'+text.slice(cursor)+'"'
    begin body

  # #!use/bin/node taiji
  @binShellDirective = ->
    if text[cursor...cursor+2]!='#!' then return

    cur = cursor
    while char and char!='\n' and char!='\r' then char = text[++cursor]

    if char=='\n'
      if char=='\r' then cursor += 2
      else cursor++
      lineno++
    else if char=='\r'
      if char=='\n' then cursor += 2
      else cursor++
      lineno++

    lineStart = cursor

    ['binShellDirective!', text[cur...cursor]]

  @moduleHeader = ->
    cur = cursor
    if not (literal('taiji') and spaces()  and  literal('language') and spaces() and
        (x=decimal()) and matchChar('.') and (y=decimal()))
      lexError 'taiji language module should begin with "taiji language x.x"'
    if (x=x.value)!='0' or (y=y.value)!='1' then error 'taiji 0.1 can not process taiji language'+x+'.'+y

    while char and char!='\n' and char!='\r' then char = text[++cursor]
    while char
      if char=='\n'
        if char=='\r' then cursor += 2
        else cursor++
        lineno++
      else if char=='\r'
        if char=='\n' then cursor += 2
        else cursor++
        lineno++
      if (char=text[cursor])!=' ' and  char!='\t' and char!='\n'  and char!='\r' then break
      while char and char!='\n' and char!='\r' then char = text[++cursor]
    {type: MODULE_HEADER, version: {main:x, minor:y}, value: text[...cursor], cursor:cur, stopCursor:cursor}

  @module = ->
    scriptDirective = ['scriptDirective!', parser.binShellDirective()]
    result = {value:['module!', scriptDirective, parser.moduleHeader(), parser.moduleBody()],
    cursor:0, stopCursor:text.length, line:1, column:0}
    result.start = result
    result

  @init = (data, cur, env) ->
    @text = text = data; cursor = cur; char = text[cursor]; lineno = 1; lineStart = 0
    token = {} # an empty token, {}.next is undefined, so nextToken will call matchToken
    # should not call matchToken() here, because the head of module need be processed differently
    # matchToken() should be called in moduleBody() instead
    memoMap = {}
    atStatementHead = true
    interolateStringNumber = 0
    @environment = environment = env
    @meetEllipsis = false
    endCursorOfDynamicBlockStack = []

  @parse = (data, root, cur, env) ->
    parser.init(data, cur, env)
    # should not call matchToken() here, because the head of module need be processed differently
    # matchToken() should be called in moduleBody() instead
    root()

  @lexError = lexError = (message) ->
    throw cursor+'('+lineno+':'+(cursor-lineStart)+'): '+'lexical error: '+message+': \n'+text[cursor-40...cursor]+'|   |'+text[cursor...cursor+40]

  @error = error = (message, tkn) ->
    tkn = tkn or token; cur = tkn.cursor
    throw cur+'('+tkn.line+':'+tkn.column+'): '+message+': \n'+text[cur-40...cur]+(text[cur...cur+40].red)

  return @

{compileExp} = require '../compiler'